name: welcome_page
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.3.2+2
  modal_progress_hud: ^0.1.3
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - icons/
    - assets/images/vatrina.png
    - assets/images/product-placeholder.png

  fonts:
  - family: Source Sans Pro
    fonts:
      - asset: assets/fonts/SourceSansPro-Regular.ttf
